import { GAME_TAGS, uniqueTags } from './content/tags';
import type { AbilityRuntimeDefinition } from './types';
import { supportAbility } from './abilityCatalogShared';

export const SUPPORT_ABILITY_DEFINITIONS = {
  mendWounds: supportAbility({
    id: 'mendWounds',
    manaCost: 5,
    cooldownMs: 3200,
    castTimeMs: 350,
    target: 'self',
    school: 'support',
    effects: [{ kind: 'heal', powerMultiplier: 1.2, flatPower: 2 }],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  fieldDressing: supportAbility({
    id: 'fieldDressing',
    manaCost: 6,
    cooldownMs: 4200,
    castTimeMs: 450,
    target: 'injuredAlly',
    school: 'support',
    effects: [{ kind: 'heal', powerMultiplier: 1.45, flatPower: 3 }],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  soothingMist: supportAbility({
    id: 'soothingMist',
    manaCost: 5,
    cooldownMs: 6200,
    castTimeMs: 700,
    target: 'allAllies',
    school: 'support',
    effects: [{ kind: 'heal', powerMultiplier: 1.2, splitDivisor: 3 }],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  rallyingCry: supportAbility({
    id: 'rallyingCry',
    manaCost: 5,
    cooldownMs: 4800,
    castTimeMs: 250,
    target: 'self',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'power',
        value: 14,
        permanent: true,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  battlePrayer: supportAbility({
    id: 'battlePrayer',
    manaCost: 6,
    cooldownMs: 5200,
    castTimeMs: 500,
    target: 'randomAlly',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'restoration',
        value: 2,
        durationMs: 8_000,
        tickIntervalMs: 1_000,
      },
      {
        kind: 'applyStatus',
        statusEffectId: 'frenzy',
        value: 16,
        durationMs: 8_000,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  warBanner: supportAbility({
    id: 'warBanner',
    manaCost: 5,
    cooldownMs: 6800,
    castTimeMs: 550,
    target: 'allAllies',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'power',
        value: 10,
        permanent: true,
      },
      {
        kind: 'applyStatus',
        statusEffectId: 'guard',
        value: 10,
        permanent: true,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  ironGuard: supportAbility({
    id: 'ironGuard',
    manaCost: 5,
    cooldownMs: 4300,
    castTimeMs: 200,
    target: 'self',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'guard',
        value: 28,
        durationMs: 4_000,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  arcWard: supportAbility({
    id: 'arcWard',
    manaCost: 6,
    cooldownMs: 5000,
    castTimeMs: 300,
    target: 'randomAlly',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'guard',
        value: 22,
        durationMs: 6_000,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  witheringHex: supportAbility({
    id: 'witheringHex',
    manaCost: 5,
    cooldownMs: 4700,
    castTimeMs: 350,
    target: 'randomEnemy',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'weakened',
        value: 16,
        permanent: true,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
  sunderArmor: supportAbility({
    id: 'sunderArmor',
    manaCost: 5,
    cooldownMs: 3900,
    castTimeMs: 150,
    target: 'enemy',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'shocked',
        value: 26,
        durationMs: 4_000,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat, GAME_TAGS.ability.singleTarget),
  }),
  enfeeblingPulse: supportAbility({
    id: 'enfeeblingPulse',
    manaCost: 6,
    cooldownMs: 7100,
    castTimeMs: 650,
    target: 'allEnemies',
    school: 'support',
    effects: [
      {
        kind: 'applyStatus',
        statusEffectId: 'weakened',
        value: 14,
        durationMs: 7_000,
      },
    ],
    tags: uniqueTags(GAME_TAGS.ability.combat),
  }),
} satisfies Record<string, AbilityRuntimeDefinition>;
