import { buildItemFromConfig } from './content/items';
import { Skill, type RecipeDefinition } from './types';

export const CRAFTED_EXPANSION_RECIPES: RecipeDefinition[] = [
  {
    id: 'craft-ashen-blade',
    name: 'Ashen Blade',
    description: "Ashen a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-blade', { id: 'crafted-ashen-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-buckler',
    name: 'Ashen Buckler',
    description: "Ashen a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-buckler', { id: 'crafted-ashen-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-hood',
    name: 'Ashen Hood',
    description: "Ashen a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-hood', { id: 'crafted-ashen-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-mantle',
    name: 'Ashen Mantle',
    description: "Ashen layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-mantle', { id: 'crafted-ashen-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ashen-vest',
    name: 'Ashen Vest',
    description: "Ashen a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-vest', { id: 'crafted-ashen-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-bracers',
    name: 'Ashen Bracers',
    description: "Ashen wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-bracers', { id: 'crafted-ashen-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-gloves',
    name: 'Ashen Gloves',
    description: "Ashen work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-gloves', { id: 'crafted-ashen-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-belt',
    name: 'Ashen Belt',
    description: "Ashen a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-belt', { id: 'crafted-ashen-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-leggings',
    name: 'Ashen Leggings',
    description: "Ashen travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-leggings', { id: 'crafted-ashen-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ashen-boots',
    name: 'Ashen Boots',
    description: "Ashen hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-boots', { id: 'crafted-ashen-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-charm',
    name: 'Ashen Charm',
    description: "Ashen a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-charm', { id: 'crafted-ashen-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ashen-cloak',
    name: 'Ashen Cloak',
    description: "Ashen a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ashen-cloak', { id: 'crafted-ashen-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-blade',
    name: 'Rift Blade',
    description: "Rift a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-blade', { id: 'crafted-rift-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-buckler',
    name: 'Rift Buckler',
    description: "Rift a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-buckler', { id: 'crafted-rift-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-hood',
    name: 'Rift Hood',
    description: "Rift a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-hood', { id: 'crafted-rift-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-mantle',
    name: 'Rift Mantle',
    description: "Rift layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-mantle', { id: 'crafted-rift-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-rift-vest',
    name: 'Rift Vest',
    description: "Rift a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-vest', { id: 'crafted-rift-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-bracers',
    name: 'Rift Bracers',
    description: "Rift wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-bracers', { id: 'crafted-rift-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-gloves',
    name: 'Rift Gloves',
    description: "Rift work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-gloves', { id: 'crafted-rift-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-belt',
    name: 'Rift Belt',
    description: "Rift a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-belt', { id: 'crafted-rift-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-leggings',
    name: 'Rift Leggings',
    description: "Rift travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-leggings', { id: 'crafted-rift-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-rift-boots',
    name: 'Rift Boots',
    description: "Rift hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-boots', { id: 'crafted-rift-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-charm',
    name: 'Rift Charm',
    description: "Rift a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-charm', { id: 'crafted-rift-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-rift-cloak',
    name: 'Rift Cloak',
    description: "Rift a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('rift-cloak', { id: 'crafted-rift-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-blade',
    name: 'Shard Blade',
    description: "Shard a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-blade', { id: 'crafted-shard-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-buckler',
    name: 'Shard Buckler',
    description: "Shard a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-buckler', { id: 'crafted-shard-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-hood',
    name: 'Shard Hood',
    description: "Shard a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-hood', { id: 'crafted-shard-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-mantle',
    name: 'Shard Mantle',
    description: "Shard layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-mantle', { id: 'crafted-shard-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-shard-vest',
    name: 'Shard Vest',
    description: "Shard a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-vest', { id: 'crafted-shard-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-bracers',
    name: 'Shard Bracers',
    description: "Shard wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-bracers', { id: 'crafted-shard-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-gloves',
    name: 'Shard Gloves',
    description: "Shard work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-gloves', { id: 'crafted-shard-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-belt',
    name: 'Shard Belt',
    description: "Shard a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-belt', { id: 'crafted-shard-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-leggings',
    name: 'Shard Leggings',
    description: "Shard travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-leggings', { id: 'crafted-shard-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-shard-boots',
    name: 'Shard Boots',
    description: "Shard hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-boots', { id: 'crafted-shard-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-charm',
    name: 'Shard Charm',
    description: "Shard a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-charm', { id: 'crafted-shard-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-shard-cloak',
    name: 'Shard Cloak',
    description: "Shard a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('shard-cloak', { id: 'crafted-shard-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-blade',
    name: 'Vale Blade',
    description: "Vale a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-blade', { id: 'crafted-vale-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-buckler',
    name: 'Vale Buckler',
    description: "Vale a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-buckler', { id: 'crafted-vale-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-hood',
    name: 'Vale Hood',
    description: "Vale a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-hood', { id: 'crafted-vale-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-mantle',
    name: 'Vale Mantle',
    description: "Vale layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-mantle', { id: 'crafted-vale-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-vale-vest',
    name: 'Vale Vest',
    description: "Vale a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-vest', { id: 'crafted-vale-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-bracers',
    name: 'Vale Bracers',
    description: "Vale wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-bracers', { id: 'crafted-vale-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-gloves',
    name: 'Vale Gloves',
    description: "Vale work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-gloves', { id: 'crafted-vale-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-belt',
    name: 'Vale Belt',
    description: "Vale a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-belt', { id: 'crafted-vale-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-leggings',
    name: 'Vale Leggings',
    description: "Vale travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-leggings', { id: 'crafted-vale-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-vale-boots',
    name: 'Vale Boots',
    description: "Vale hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-boots', { id: 'crafted-vale-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-charm',
    name: 'Vale Charm',
    description: "Vale a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-charm', { id: 'crafted-vale-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-vale-cloak',
    name: 'Vale Cloak',
    description: "Vale a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('vale-cloak', { id: 'crafted-vale-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-blade',
    name: 'Ironbound Blade',
    description: "Ironbound a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-blade', { id: 'crafted-ironbound-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-buckler',
    name: 'Ironbound Buckler',
    description: "Ironbound a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-buckler', { id: 'crafted-ironbound-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-hood',
    name: 'Ironbound Hood',
    description: "Ironbound a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-hood', { id: 'crafted-ironbound-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-mantle',
    name: 'Ironbound Mantle',
    description: "Ironbound layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-mantle', { id: 'crafted-ironbound-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ironbound-vest',
    name: 'Ironbound Vest',
    description: "Ironbound a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-vest', { id: 'crafted-ironbound-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-bracers',
    name: 'Ironbound Bracers',
    description: "Ironbound wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-bracers', { id: 'crafted-ironbound-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-gloves',
    name: 'Ironbound Gloves',
    description: "Ironbound work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-gloves', { id: 'crafted-ironbound-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-belt',
    name: 'Ironbound Belt',
    description: "Ironbound a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-belt', { id: 'crafted-ironbound-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-leggings',
    name: 'Ironbound Leggings',
    description: "Ironbound travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-leggings', { id: 'crafted-ironbound-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ironbound-boots',
    name: 'Ironbound Boots',
    description: "Ironbound hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-boots', { id: 'crafted-ironbound-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-charm',
    name: 'Ironbound Charm',
    description: "Ironbound a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-charm', { id: 'crafted-ironbound-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ironbound-cloak',
    name: 'Ironbound Cloak',
    description: "Ironbound a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ironbound-cloak', { id: 'crafted-ironbound-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-blade',
    name: 'Storm Blade',
    description: "Storm a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-blade', { id: 'crafted-storm-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-buckler',
    name: 'Storm Buckler',
    description: "Storm a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-buckler', { id: 'crafted-storm-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-hood',
    name: 'Storm Hood',
    description: "Storm a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-hood', { id: 'crafted-storm-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-mantle',
    name: 'Storm Mantle',
    description: "Storm layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-mantle', { id: 'crafted-storm-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-storm-vest',
    name: 'Storm Vest',
    description: "Storm a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-vest', { id: 'crafted-storm-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-bracers',
    name: 'Storm Bracers',
    description: "Storm wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-bracers', { id: 'crafted-storm-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-gloves',
    name: 'Storm Gloves',
    description: "Storm work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-gloves', { id: 'crafted-storm-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-belt',
    name: 'Storm Belt',
    description: "Storm a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-belt', { id: 'crafted-storm-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-leggings',
    name: 'Storm Leggings',
    description: "Storm travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-leggings', { id: 'crafted-storm-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-storm-boots',
    name: 'Storm Boots',
    description: "Storm hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-boots', { id: 'crafted-storm-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-charm',
    name: 'Storm Charm',
    description: "Storm a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-charm', { id: 'crafted-storm-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-storm-cloak',
    name: 'Storm Cloak',
    description: "Storm a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('storm-cloak', { id: 'crafted-storm-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-blade',
    name: 'Ember Blade',
    description: "Ember a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-blade', { id: 'crafted-ember-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-buckler',
    name: 'Ember Buckler',
    description: "Ember a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-buckler', { id: 'crafted-ember-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-hood',
    name: 'Ember Hood',
    description: "Ember a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-hood', { id: 'crafted-ember-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-mantle',
    name: 'Ember Mantle',
    description: "Ember layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-mantle', { id: 'crafted-ember-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ember-vest',
    name: 'Ember Vest',
    description: "Ember a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-vest', { id: 'crafted-ember-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-bracers',
    name: 'Ember Bracers',
    description: "Ember wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-bracers', { id: 'crafted-ember-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-gloves',
    name: 'Ember Gloves',
    description: "Ember work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-gloves', { id: 'crafted-ember-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-belt',
    name: 'Ember Belt',
    description: "Ember a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-belt', { id: 'crafted-ember-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-leggings',
    name: 'Ember Leggings',
    description: "Ember travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-leggings', { id: 'crafted-ember-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-ember-boots',
    name: 'Ember Boots',
    description: "Ember hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-boots', { id: 'crafted-ember-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-charm',
    name: 'Ember Charm',
    description: "Ember a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-charm', { id: 'crafted-ember-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-ember-cloak',
    name: 'Ember Cloak',
    description: "Ember a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('ember-cloak', { id: 'crafted-ember-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-blade',
    name: 'Hollow Blade',
    description: "Hollow a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-blade', { id: 'crafted-hollow-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-buckler',
    name: 'Hollow Buckler',
    description: "Hollow a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-buckler', { id: 'crafted-hollow-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-hood',
    name: 'Hollow Hood',
    description: "Hollow a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-hood', { id: 'crafted-hollow-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-mantle',
    name: 'Hollow Mantle',
    description: "Hollow layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-mantle', { id: 'crafted-hollow-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-hollow-vest',
    name: 'Hollow Vest',
    description: "Hollow a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-vest', { id: 'crafted-hollow-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-bracers',
    name: 'Hollow Bracers',
    description: "Hollow wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-bracers', { id: 'crafted-hollow-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-gloves',
    name: 'Hollow Gloves',
    description: "Hollow work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-gloves', { id: 'crafted-hollow-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-belt',
    name: 'Hollow Belt',
    description: "Hollow a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-belt', { id: 'crafted-hollow-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-leggings',
    name: 'Hollow Leggings',
    description: "Hollow travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-leggings', { id: 'crafted-hollow-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-hollow-boots',
    name: 'Hollow Boots',
    description: "Hollow hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-boots', { id: 'crafted-hollow-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-charm',
    name: 'Hollow Charm',
    description: "Hollow a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-charm', { id: 'crafted-hollow-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-hollow-cloak',
    name: 'Hollow Cloak',
    description: "Hollow a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('hollow-cloak', { id: 'crafted-hollow-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-blade',
    name: 'Warden Blade',
    description: "Warden a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-blade', { id: 'crafted-warden-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-buckler',
    name: 'Warden Buckler',
    description: "Warden a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-buckler', { id: 'crafted-warden-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-hood',
    name: 'Warden Hood',
    description: "Warden a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-hood', { id: 'crafted-warden-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-mantle',
    name: 'Warden Mantle',
    description: "Warden layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-mantle', { id: 'crafted-warden-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-warden-vest',
    name: 'Warden Vest',
    description: "Warden a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-vest', { id: 'crafted-warden-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-bracers',
    name: 'Warden Bracers',
    description: "Warden wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-bracers', { id: 'crafted-warden-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-gloves',
    name: 'Warden Gloves',
    description: "Warden work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-gloves', { id: 'crafted-warden-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-belt',
    name: 'Warden Belt',
    description: "Warden a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-belt', { id: 'crafted-warden-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-leggings',
    name: 'Warden Leggings',
    description: "Warden travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-leggings', { id: 'crafted-warden-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-warden-boots',
    name: 'Warden Boots',
    description: "Warden hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-boots', { id: 'crafted-warden-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-charm',
    name: 'Warden Charm',
    description: "Warden a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-charm', { id: 'crafted-warden-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-warden-cloak',
    name: 'Warden Cloak',
    description: "Warden a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('warden-cloak', { id: 'crafted-warden-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-blade',
    name: 'Void Blade',
    description: "Void a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-blade', { id: 'crafted-void-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-buckler',
    name: 'Void Buckler',
    description: "Void a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-buckler', { id: 'crafted-void-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-hood',
    name: 'Void Hood',
    description: "Void a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-hood', { id: 'crafted-void-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-mantle',
    name: 'Void Mantle',
    description: "Void layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-mantle', { id: 'crafted-void-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-void-vest',
    name: 'Void Vest',
    description: "Void a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-vest', { id: 'crafted-void-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-bracers',
    name: 'Void Bracers',
    description: "Void wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-bracers', { id: 'crafted-void-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-gloves',
    name: 'Void Gloves',
    description: "Void work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-gloves', { id: 'crafted-void-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-belt',
    name: 'Void Belt',
    description: "Void a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-belt', { id: 'crafted-void-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-leggings',
    name: 'Void Leggings',
    description: "Void travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-leggings', { id: 'crafted-void-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-void-boots',
    name: 'Void Boots',
    description: "Void hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-boots', { id: 'crafted-void-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-charm',
    name: 'Void Charm',
    description: "Void a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-charm', { id: 'crafted-void-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-void-cloak',
    name: 'Void Cloak',
    description: "Void a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('void-cloak', { id: 'crafted-void-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-blade',
    name: 'Dawn Blade',
    description: "Dawn a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-blade', { id: 'crafted-dawn-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-buckler',
    name: 'Dawn Buckler',
    description: "Dawn a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-buckler', { id: 'crafted-dawn-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-hood',
    name: 'Dawn Hood',
    description: "Dawn a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-hood', { id: 'crafted-dawn-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-mantle',
    name: 'Dawn Mantle',
    description: "Dawn layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-mantle', { id: 'crafted-dawn-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-dawn-vest',
    name: 'Dawn Vest',
    description: "Dawn a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-vest', { id: 'crafted-dawn-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-bracers',
    name: 'Dawn Bracers',
    description: "Dawn wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-bracers', { id: 'crafted-dawn-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-gloves',
    name: 'Dawn Gloves',
    description: "Dawn work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-gloves', { id: 'crafted-dawn-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-belt',
    name: 'Dawn Belt',
    description: "Dawn a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-belt', { id: 'crafted-dawn-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-leggings',
    name: 'Dawn Leggings',
    description: "Dawn travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-leggings', { id: 'crafted-dawn-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-dawn-boots',
    name: 'Dawn Boots',
    description: "Dawn hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-boots', { id: 'crafted-dawn-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-charm',
    name: 'Dawn Charm',
    description: "Dawn a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-charm', { id: 'crafted-dawn-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dawn-cloak',
    name: 'Dawn Cloak',
    description: "Dawn a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dawn-cloak', { id: 'crafted-dawn-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-blade',
    name: 'Dusk Blade',
    description: "Dusk a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-blade', { id: 'crafted-dusk-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-buckler',
    name: 'Dusk Buckler',
    description: "Dusk a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-buckler', { id: 'crafted-dusk-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-hood',
    name: 'Dusk Hood',
    description: "Dusk a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-hood', { id: 'crafted-dusk-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-mantle',
    name: 'Dusk Mantle',
    description: "Dusk layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-mantle', { id: 'crafted-dusk-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-dusk-vest',
    name: 'Dusk Vest',
    description: "Dusk a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-vest', { id: 'crafted-dusk-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-bracers',
    name: 'Dusk Bracers',
    description: "Dusk wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-bracers', { id: 'crafted-dusk-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-gloves',
    name: 'Dusk Gloves',
    description: "Dusk work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-gloves', { id: 'crafted-dusk-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-belt',
    name: 'Dusk Belt',
    description: "Dusk a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-belt', { id: 'crafted-dusk-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-leggings',
    name: 'Dusk Leggings',
    description: "Dusk travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-leggings', { id: 'crafted-dusk-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-dusk-boots',
    name: 'Dusk Boots',
    description: "Dusk hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-boots', { id: 'crafted-dusk-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-charm',
    name: 'Dusk Charm',
    description: "Dusk a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-charm', { id: 'crafted-dusk-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-dusk-cloak',
    name: 'Dusk Cloak',
    description: "Dusk a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('dusk-cloak', { id: 'crafted-dusk-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-blade',
    name: 'Moss Blade',
    description: "Moss a tempered blade shaped for shard-road skirmishes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-blade', { id: 'crafted-moss-blade' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 2 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-buckler',
    name: 'Moss Buckler',
    description: "Moss a compact buckler braced against splintered steel.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-buckler', { id: 'crafted-moss-buckler' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'logs', name: 'Logs', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-hood',
    name: 'Moss Hood',
    description: "Moss a close hood cut to keep ash and glare from your eyes.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-hood', { id: 'crafted-moss-hood' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-mantle',
    name: 'Moss Mantle',
    description: "Moss layered shoulders made for wind and falling cinders.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-mantle', { id: 'crafted-moss-mantle' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 2 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-moss-vest',
    name: 'Moss Vest',
    description: "Moss a reinforced vest fit for labor under a broken sky.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-vest', { id: 'crafted-moss-vest' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 4 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 4 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-bracers',
    name: 'Moss Bracers',
    description: "Moss wrist guards built for rope, stone, and sudden blows.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-bracers', { id: 'crafted-moss-bracers' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-gloves',
    name: 'Moss Gloves',
    description: "Moss work gloves stitched for salvage and cold iron.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-gloves', { id: 'crafted-moss-gloves' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-belt',
    name: 'Moss Belt',
    description: "Moss a stout belt carrying tools, charms, and spare cord.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-belt', { id: 'crafted-moss-belt' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-leggings',
    name: 'Moss Leggings',
    description: "Moss travel leggings meant for brush, rubble, and steep climbs.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-leggings', { id: 'crafted-moss-leggings' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 2 },
    ],
  },
  {
    id: 'craft-moss-boots',
    name: 'Moss Boots',
    description: "Moss hard-worn boots for fractured roads and slick ruins.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-boots', { id: 'crafted-moss-boots' }),
    ingredients: [
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 3 },
      { itemKey: 'sticks', name: 'Sticks', quantity: 1 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-charm',
    name: 'Moss Charm',
    description: "Moss a traveler's charm threaded to steady the heart near Aether.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-charm', { id: 'crafted-moss-charm' }),
    ingredients: [
      { itemKey: 'iron-ingot', name: 'Iron Ingot', quantity: 1 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 2 },
      { itemKey: 'cloth', name: 'Cloth', quantity: 1 },
    ],
  },
  {
    id: 'craft-moss-cloak',
    name: 'Moss Cloak',
    description: "Moss a weather cloak that breaks rain, soot, and drifting ash.",
    skill: Skill.Crafting as const,
    output: buildItemFromConfig('moss-cloak', { id: 'crafted-moss-cloak' }),
    ingredients: [
      { itemKey: 'cloth', name: 'Cloth', quantity: 3 },
      { itemKey: 'arcane-dust', name: 'Aether Dust', quantity: 1 },
      { itemKey: 'leather-scraps', name: 'Leather Scraps', quantity: 1 },
    ],
  },
];


