import { buildItemFromConfig } from './content/items';
import { Skill, type RecipeDefinition } from './types';

const COOKING_FUEL_OPTIONS = [
  { itemKey: 'coal', name: 'Coal', quantity: 1 },
  { itemKey: 'logs', name: 'Logs', quantity: 2 },
  { itemKey: 'sticks', name: 'Sticks', quantity: 8 },
] as const;

export const HARVEST_COOKING_RECIPES: RecipeDefinition[] = [
  {
    id: 'cook-garden-stew',
    name: 'Garden Stew',
    description: 'A soft stew of greens and roots simmered over camp coals.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('garden-stew'),
    ingredients: [
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-root-medley',
    name: 'Root Medley',
    description: 'Roasted roots and leek dressed with wild herbs.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('root-medley'),
    ingredients: [
      { itemKey: 'beet', name: 'Beet', quantity: 1 },
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
      { itemKey: 'leek', name: 'Leek', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-pepper-skillet',
    name: 'Pepper Skillet',
    description: 'A bright skillet of pepper, tomato, and garlic.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('pepper-skillet'),
    ingredients: [
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-cabbage-broth',
    name: 'Cabbage Broth',
    description: 'A clear broth steeped with cabbage leaves and sharp garlic.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('cabbage-broth'),
    ingredients: [
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-herb-salad',
    name: 'Herb Salad',
    description: 'Fresh chopped greens with tomato and a little citrus.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('herb-salad'),
    ingredients: [
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-cherry-compote',
    name: 'Cherry Compote',
    description: 'A sweet pan-cooked compote of orchard fruit.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('cherry-compote'),
    ingredients: [
      { itemKey: 'cherry', name: 'Cherry', quantity: 1 },
      { itemKey: 'apple', name: 'Apple', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-garlic-leek-soup',
    name: 'Garlic Leek Soup',
    description: 'A rich soup that carries garlic warmth into the night.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('garlic-leek-soup'),
    ingredients: [
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
      { itemKey: 'leek', name: 'Leek', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-lemon-pea-mix',
    name: 'Lemon Pea Mix',
    description: 'Tender peas tossed with lemon and fragrant herbs.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('lemon-pea-mix'),
    ingredients: [
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
      { itemKey: 'peas', name: 'Peas', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-ratatouille',
    name: 'Ratatouille',
    description: 'A thick pan of aubergine, tomato, and pepper.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('ratatouille'),
    ingredients: [
      { itemKey: 'aubergine', name: 'Aubergine', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-orchard-mix',
    name: 'Orchard Mix',
    description: 'A cooling mix of orchard fruit finished with citrus.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('orchard-mix'),
    ingredients: [
      { itemKey: 'apple', name: 'Apple', quantity: 1 },
      { itemKey: 'cherry', name: 'Cherry', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-beet-tonic',
    name: 'Beet Tonic',
    description: 'A vibrant beet tonic simmered with herbs and lemon.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('beet-tonic'),
    ingredients: [
      { itemKey: 'beet', name: 'Beet', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-carrot-braise',
    name: 'Carrot Braise',
    description: 'Braised carrots softened with garlic and herb steam.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('carrot-braise'),
    ingredients: [
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-summer-salad',
    name: 'Summer Salad',
    description: 'A juicy summer salad of pepper, peas, and tomato.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('summer-salad'),
    ingredients: [
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
      { itemKey: 'peas', name: 'Peas', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-harvest-succotash',
    name: 'Harvest Succotash',
    description: 'A camp succotash built from the best of the patch.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('harvest-succotash'),
    ingredients: [
      { itemKey: 'peas', name: 'Peas', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-lemon-herb-broth',
    name: 'Lemon Herb Broth',
    description: 'A bright broth that steadies breath and clears dust.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('lemon-herb-broth'),
    ingredients: [
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-stuffed-aubergine',
    name: 'Stuffed Aubergine',
    description: 'Aubergine packed with pepper and tomato.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('stuffed-aubergine'),
    ingredients: [
      { itemKey: 'aubergine', name: 'Aubergine', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-rustic-veg-mash',
    name: 'Rustic Veg Mash',
    description: 'A rough mash of boiled roots and greens.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('rustic-veg-mash'),
    ingredients: [
      { itemKey: 'beet', name: 'Beet', quantity: 1 },
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-peasant-stew',
    name: 'Peasant Stew',
    description: 'A thick peasant stew of greens and field peas.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('peasant-stew'),
    ingredients: [
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'leek', name: 'Leek', quantity: 1 },
      { itemKey: 'peas', name: 'Peas', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-cherry-apple-crisp',
    name: 'Cherry Apple Crisp',
    description: 'A sweet camp crisp of cherry and apple with earthy depth.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('cherry-apple-crisp'),
    ingredients: [
      { itemKey: 'cherry', name: 'Cherry', quantity: 1 },
      { itemKey: 'apple', name: 'Apple', quantity: 1 },
      { itemKey: 'beet', name: 'Beet', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-hearty-veg-stew',
    name: 'Hearty Veg Stew',
    description: 'A hearty vegetable stew for long marches and longer watches.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('hearty-veg-stew'),
    ingredients: [
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
      { itemKey: 'aubergine', name: 'Aubergine', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-herb-roasted-meat',
    name: 'Herb Roasted Meat',
    description: 'Roasted meat rubbed with herbs and seared garlic.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('herb-roasted-meat'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-pepper-steak',
    name: 'Pepper Steak',
    description: 'A pepper-crusted steak finished in a hot pan.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('pepper-steak'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-cabbage-meat-stew',
    name: 'Cabbage Meat Stew',
    description: 'A dense stew of meat, cabbage, and leek.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('cabbage-meat-stew'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
      { itemKey: 'leek', name: 'Leek', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-garlic-meat-skewers',
    name: 'Garlic Meat Skewers',
    description: 'Charred skewers basted with garlic and pepper.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('garlic-meat-skewers'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
      { itemKey: 'pepper', name: 'Pepper', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-cherry-glazed-meat',
    name: 'Cherry Glazed Meat',
    description: 'A sweet-sour glaze laid over roasted cuts.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('cherry-glazed-meat'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'cherry', name: 'Cherry', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-lemon-cutlet',
    name: 'Lemon Cutlet',
    description: 'A bright cutlet with lemon oil and wild herbs.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('lemon-cutlet'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'lemon', name: 'Lemon', quantity: 1 },
      { itemKey: 'herbs', name: 'Herbs', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-hunter-stew',
    name: 'Hunter Stew',
    description: 'A hunter stew meant to restore strength after the chase.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('hunter-stew'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'carrot', name: 'Carrot', quantity: 1 },
      { itemKey: 'cabbage', name: 'Cabbage', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-meat-and-peas-braise',
    name: 'Meat and Peas Braise',
    description: 'Braised meat folded with peas and garlic.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('meat-and-peas-braise'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'peas', name: 'Peas', quantity: 1 },
      { itemKey: 'garlic', name: 'Garlic', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-aubergine-meat-skillet',
    name: 'Aubergine Meat Skillet',
    description: 'A rich skillet of meat, aubergine, and tomato.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('aubergine-meat-skillet'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'aubergine', name: 'Aubergine', quantity: 1 },
      { itemKey: 'tomato', name: 'Tomato', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
  {
    id: 'cook-orchard-roast',
    name: 'Orchard Roast',
    description: 'Roasted meat glazed with orchard fruit.',
    skill: Skill.Cooking,
    output: buildItemFromConfig('orchard-roast'),
    ingredients: [
      { itemKey: 'meat', name: 'Meat', quantity: 1 },
      { itemKey: 'apple', name: 'Apple', quantity: 1 },
      { itemKey: 'cherry', name: 'Cherry', quantity: 1 },
    ],
    fuelOptions: [...COOKING_FUEL_OPTIONS],
  },
];
