import { defineGameConfig } from './src/game/gameConfigSchema';

const gameConfig = defineGameConfig({
  balance: {
    combat: {
      // Shared baseline cooldown before attack-speed modifiers scale timing.
      globalCooldownMs: 2000,
    },
    player: {
      // Highest level the player can reach through normal progression.
      maxLevel: 100,
      baseStats: {
        level1: {
          // Starting maximum HP for a level 1 player before gear bonuses.
          maxHp: 150,
          // Starting attack for a level 1 player before gear bonuses.
          attack: 50,
          // Starting defense for a level 1 player before gear bonuses.
          defense: 35,
        },
        level100: {
          // Maximum HP anchor used when interpolating player stats to level 100.
          maxHp: 4000,
          // Attack anchor used when interpolating player stats to level 100.
          attack: 800,
          // Defense anchor used when interpolating player stats to level 100.
          defense: 200,
        },
      },
    },
    enemy: {
      baseStats: {
        level1: {
          // Starting HP anchor for a level 1 enemy before rarity scaling.
          maxHp: 150,
          // Starting attack anchor for a level 1 enemy before rarity scaling.
          attack: 50,
          // Starting defense anchor for a level 1 enemy before rarity scaling.
          defense: 35,
        },
        level100: {
          // HP anchor used when interpolating enemy stats to level 100.
          maxHp: 5000,
          // Attack anchor used when interpolating enemy stats to level 100.
          attack: 1600,
          // Defense anchor used when interpolating enemy stats to level 100.
          defense: 1100,
        },
      },
      // Extra fraction of the level-100 stat anchor added per enemy level above 100.
      postLevel100PerLevel: 0.1,
      rarityMultiplier: {
        // Baseline multiplier for common enemies.
        common: 1,
        // Stat multiplier for uncommon enemies.
        uncommon: 1.12,
        // Stat multiplier for rare enemies.
        rare: 1.27,
        // Stat multiplier for epic enemies.
        epic: 1.45,
        // Stat multiplier for legendary enemies.
        legendary: 1.72,
      },
    },
    items: {
      // Highest item level generated by the standard progression curve.
      maxLevel: 100,
      baseStat: {
        // Main-stat floor for generated equippables at item level 1.
        level1: 1,
        // Main-stat ceiling for generated equippables at item level 100.
        level100: 1000,
      },
      secondaryStat: {
        // Secondary-stat floor for generated equippables at item level 1.
        level1: 1,
        // Secondary-stat ceiling for generated equippables at item level 100.
        level100: 10,
        // Hard cap applied to effective gear-derived secondary bonuses.
        cap: 75,
      },
      modification: {
        reforge: {
          // Flat gold cost to start a reforge action.
          baseCost: 18,
          // Extra gold cost added per item tier.
          perTier: 6,
          // Extra gold cost added per rarity step.
          perRarity: 16,
        },
        enchant: {
          // Flat gold cost to start an enchant action.
          baseCost: 28,
          // Extra gold cost added per item tier.
          perTier: 8,
          // Extra gold cost added per rarity step.
          perRarity: 22,
        },
        corrupt: {
          // Flat gold cost to start a corruption action.
          baseCost: 40,
          // Extra gold cost added per item tier.
          perTier: 10,
          // Extra gold cost added per rarity step.
          perRarity: 28,
          // Chance that corruption destroys the item instead of upgrading it.
          breakChance: 0.05,
          // Stat bonus multiplier applied when corruption succeeds.
          statBonus: 0.1,
        },
      },
    },
    economy: {
      townBuyPrice: {
        // Minimum gold price a town stock entry can cost after all scaling.
        minimum: 10,
        // Extra town-only price multiplier added per item tier above level 1.
        perTier: 0.1,
        rarityMultiplier: {
          // Buy-price multiplier for common town stock entries.
          common: 2,
          // Buy-price multiplier for uncommon town stock entries.
          uncommon: 3,
          // Buy-price multiplier for rare town stock entries.
          rare: 6,
          // Buy-price multiplier for epic town stock entries.
          epic: 12,
          // Buy-price multiplier for legendary town stock entries.
          legendary: 24,
        },
        consumable: {
          // Minimum gold price for consumable town stock entries.
          minimum: 10,
          // Base buy-price multiplier applied to consumable town stock entries.
          baseMultiplier: 6,
          // Extra town-only price multiplier added per item tier above level 1.
          perTier: 0.1,
          rarityMultiplier: {
            // Buy-price multiplier for common consumable town stock entries.
            common: 1,
            // Buy-price multiplier for uncommon consumable town stock entries.
            uncommon: 1.1,
            // Buy-price multiplier for rare consumable town stock entries.
            rare: 1.25,
            // Buy-price multiplier for epic consumable town stock entries.
            epic: 1.45,
            // Buy-price multiplier for legendary consumable town stock entries.
            legendary: 1.75,
          },
        },
        consumableCraftedFood: {
          // Minimum gold price for crafted-food consumable town stock entries.
          minimum: 10,
          // Base buy-price multiplier applied to crafted-food consumables.
          baseMultiplier: 9,
          // Extra town-only price multiplier added per item tier above level 1.
          perTier: 0.1,
          rarityMultiplier: {
            // Buy-price multiplier for common crafted-food consumables.
            common: 1,
            // Buy-price multiplier for uncommon crafted-food consumables.
            uncommon: 1.1,
            // Buy-price multiplier for rare crafted-food consumables.
            rare: 1.25,
            // Buy-price multiplier for epic crafted-food consumables.
            epic: 1.45,
            // Buy-price multiplier for legendary crafted-food consumables.
            legendary: 1.75,
          },
        },
      },
    },
  },
  progression: {
    playerXp: {
      // Base XP contribution used when enemy XP rewards are derived.
      enemyBase: 20,
      // XP needed for the first player level-up.
      firstLevelRequirement: 20,
      // XP needed for the final standard level-up before level cap.
      lastLevelRequirement: 20000000,
      // XP needed for the first mastery level once normal leveling is complete.
      masteryBaseRequirement: 25000000,
      // Percentage growth applied to each subsequent mastery XP requirement.
      masteryGrowthRate: 0.05,
      levelDifference: {
        // XP penalty applied for each enemy tier below the player tier.
        penaltyPerLevelBelowPlayer: 0.2,
        // Maximum number of lower enemy tiers that reduce XP rewards.
        maxPenaltyLevels: 5,
        // XP bonus applied for each enemy tier above the player tier.
        bonusPerLevelAbovePlayer: 0.1,
        // Maximum number of higher enemy tiers that increase XP rewards.
        maxBonusLevels: 10,
      },
    },
    gatheringBonus: {
      // Additional gathering bonus gained per skill level.
      perLevel: 0.01,
      // Maximum gathering bonus allowed from progression.
      max: 1,
    },
    itemRarity: {
      // Chance to upgrade a generated item roll into legendary rarity.
      legendary: 0.0002,
      // Chance to upgrade a generated item roll into epic rarity.
      epic: 0.005,
      // Chance to upgrade a generated item roll into rare rarity.
      rare: 0.05,
      // Chance to upgrade a generated item roll into uncommon rarity.
      uncommon: 0.3,
    },
    itemRarityScaling: {
      // Bonus rarity chance gained per item tier.
      bonusPerTier: 0.0025,
      // Maximum rarity chance bonus from item-tier scaling.
      bonusMax: 0.06,
      // Additional rarity multipliers applied to each ascending rarity check.
      rarityBonusMultipliers: {
        uncommon: 1,
        rare: 0.45,
        epic: 0.2,
        legendary: 0.08,
      },
    },
  },
  worldClock: {
    // Real milliseconds required for one complete 24-hour in-game day.
    dayDurationMs: 5 * 60_000,
  },
  worldGeneration: {
    terrain: {
      // Chance weight for generating rift terrain.
      rift: 0.04,
      // Chance weight for generating blasted terrain.
      blasted: 0.04,
      // Chance weight for generating mountain terrain.
      mountain: 0.06,
      // Chance weight for generating highlands terrain.
      highlands: 0.07,
      // Chance weight for generating forest terrain.
      forest: 0.1,
      // Chance weight for generating grove terrain.
      grove: 0.07,
      // Chance weight for generating swamp terrain.
      swamp: 0.05,
      // Chance weight for generating marsh terrain.
      marsh: 0.06,
      // Chance weight for generating dunes terrain.
      dunes: 0.04,
      // Chance weight for generating desert terrain.
      desert: 0.08,
      // Chance weight for generating badlands terrain.
      badlands: 0.05,
      // Chance weight for generating meadow terrain.
      meadow: 0.08,
      // Chance weight for generating plains terrain.
      plains: 0.13,
      // Chance weight for generating steppe terrain.
      steppe: 0.13,
    },
    structure: {
      // Global roll thresholds for structures that bypass terrain-based selection.
      globalAppearanceThreshold: {
        // Chance threshold for camp structures on terrain-based noise roll.
        camp: 0.96,
        // Chance threshold for workshop structures on terrain-based noise roll.
        workshop: 0.964,
        // Chance threshold for furnace structures on terrain-based noise roll.
        furnace: 0.968,
        // Chance threshold for mana-font structures on terrain-based noise roll.
        'mana-font': 0.972,
        // Chance threshold for rune-forge structures on terrain-based noise roll.
        'rune-forge': 0.98,
        // Chance threshold for forge structures on terrain-based noise roll.
        forge: 0.984,
        // Chance threshold for town structures on terrain-based noise roll.
        town: 0.976,
        // Chance threshold for corruption altar structures on terrain-based noise roll.
        'corruption-altar': 0.988,
        // Chance threshold for dungeon structures on terrain-based noise roll.
        dungeon: 0.992,
      },
      // Terrain-based thresholds for resource-ish structures (higher roll keeps empty).
      appearanceChanceByTerrain: {
        // Tree spawns become available at higher structure rolls on forest tiles.
        tree: {
          forest: 0.86,
        },
        // Tin-ore spawns are more likely on plains and forest.
        'tin-ore': {
          plains: 0.86,
          forest: 0.845,
        },
        // Iron-ore spawns are more likely on swamp and forest.
        'iron-ore': {
          swamp: 0.82,
          forest: 0.82,
        },
        // Copper-ore spawns prefer plains and desert terrain.
        'copper-ore': {
          plains: 0.84,
          desert: 0.84,
        },
        // Gold-ore spawns are best on desert tiles.
        'gold-ore': {
          desert: 0.855,
        },
        // Platinum-ore spawns appear more on swamp and desert.
        'platinum-ore': {
          swamp: 0.84,
          desert: 0.845,
        },
        // Coal-ore spawns occur most often on desert terrain.
        'coal-ore': {
          desert: 0.81,
        },
        // Flax-field spawns tilt toward meadow, plains, and grove.
        flax: {
          meadow: 0.84,
          plains: 0.83,
          grove: 0.825,
        },
        // Herbs spawns support multiple terrain clusters.
        herbs: {
          meadow: 0.84,
          plains: 0.89,
          grove: 0.875,
          swamp: 0.87,
        },
        // Lake spawns are most common on plains.
        lake: {
          plains: 0.79,
        },
        // Pond spawns are most common on swamps.
        pond: {
          swamp: 0.81,
        },
      },
    },
    enemySpawn: {
      // Base chance that an eligible non-structure tile spawns a hostile encounter.
      tile: 0.2,
    },
    ambush: {
      // Chance to trigger an ambush when moving through the night, per hex entered.
      chance: 0.002,
    },
    loot: {
      // Chance that a dungeon tile rolls a loot cache.
      dungeon: 0.7,
      // Base chance that a guarded tile rolls loot.
      guardedBase: 0.3,
      // Extra guarded-loot chance gained per enemy tier.
      guardedPerTier: 0.02,
      // Maximum loot-roll chance for guarded tiles.
      guardedMax: 0.48,
      // Loot-roll chance for unguarded tiles.
      unguarded: 0.015,
      // Bonus chance that a loot roll upgrades into a better cache.
      bonusCache: 0.18,
    },
    generatedItemKind: {
      // Weight for generating an artifact from world-drop item rolls.
      artifact: 0.06,
      // Weight for generating a weapon from world-drop item rolls.
      weapon: 0.1,
      // Weight for generating an offhand item from world-drop item rolls.
      offhand: 0.1,
      // Weight for generating armor from world-drop item rolls.
      armor: 0.12,
      // Weight for generating a consumable from world-drop item rolls.
      consumable: 0.62,
    },
    generatedItem: {
      // Minimum item rarity assigned when generating from dungeon structures.
      dungeonMinimumRarity: 'rare',
      // Extra tier used when evaluating generated artifact rarity.
      artifactTierBonus: 1,
      // Fallback consumable for the highest world-gear loot band.
      fallbackConsumable: 'trail-ration',
    },
  },
  events: {
    bloodMoon: {
      // Daily chance that a blood moon activates.
      activation: 0.02,
      // Spawn chance for extra blood-moon enemies near the player.
      enemySpawnNear: 0.82,
      // Spawn chance for extra blood-moon enemies at mid distance.
      enemySpawnMid: 0.58,
      // Spawn chance for extra blood-moon enemies farther away.
      enemySpawnFar: 0.36,
      // Base chance for blood-moon enemies to add an extra loot drop.
      bonusLootExtraDropBase: 0.45,
      // Extra drop chance added per rarity step during a blood moon.
      bonusLootExtraDropPerRarity: 0.07,
    },
    harvestMoon: {
      // Daily chance that a harvest moon activates.
      activation: 0.02,
      // Spawn chance for extra harvest resources near the player.
      resourceSpawnNear: 0.8,
      // Spawn chance for extra harvest resources farther away.
      resourceSpawnFar: 0.45,
      resourceType: {
        // Weight for herb-patch harvest moon spawns.
        herbs: 0.4285714286,
        // Weight for tree harvest moon spawns.
        tree: 0.1428571429,
        // Weight for copper-vein harvest moon spawns.
        'copper-ore': 0.1428571429,
        // Weight for iron-vein harvest moon spawns.
        'iron-ore': 0.1428571429,
        // Weight for coal-vein harvest moon spawns.
        'coal-ore': 0.1428571429,
      },
    },
    earthshake: {
      // Daily chance that an earthshake event activates.
      activation: 0.02,
    },
  },
  drops: {
    enemyGold: {
      // Base chance for an enemy to drop gold.
      base: 0.22,
      // Extra gold-drop chance added per enemy tier.
      perTier: 0.06,
      // Extra gold-drop chance added per enemy rarity step.
      perRarity: 0.08,
      // Extra gold-drop chance added for elite enemies.
      eliteBonus: 0.08,
      // Maximum gold-drop chance after modifiers.
      max: 0.9,
      // Forced gold-drop chance during blood moon bonus rolls.
      bloodMoon: 1,
      boss: {
        // Minimum quantity for any world-boss gold drop.
        minimumQuantity: 40,
        // Extra gold for each world-boss tier above base.
        tierScaling: 12,
        // Additional random gold added to boss drops.
        randomRange: 40,
      },
      quantity: {
        // Minimum quantity for standard enemy-gold drops.
        minimum: 1,
        // Base weight from enemy tier in the standard gold quantity roll.
        tierWeight: 1,
        // Base weight from enemy rarity in the standard gold quantity roll.
        rarityWeight: 1,
        // Base random gold range for standard drops.
        randomBase: 5,
        // Extra random gold range added per enemy rarity step.
        randomRarityWeight: 2,
      },
      bloodMoonMultiplier: {
        // Multiplies standard gold quantity when blood moon is active.
        quantity: 2.5,
        // Adds an extra tier-weighted gold bonus during blood moon.
        tierWeight: 1,
      },
    },
    enemyRecipe: {
      // Base chance for an enemy to drop a recipe page.
      base: 0.08,
      // Extra recipe-drop chance added per enemy tier.
      perTier: 0.025,
      // Extra recipe-drop chance added per enemy rarity step.
      perRarity: 0.05,
      // Maximum recipe-drop chance outside blood moon bonuses.
      max: 0.5,
      // Additional recipe-drop chance during blood moon bonus rolls.
      bloodMoonBonus: 0.25,
      // Maximum recipe-drop chance during blood moon bonus rolls.
      bloodMoonMax: 1,
    },
    homeScroll: {
      // Base chance for a home scroll drop.
      base: 0.02,
      // Extra home-scroll drop chance added per rarity step.
      perRarity: 0.0125,
      // Maximum home-scroll drop chance.
      max: 0.1,
    },
    enemyItem: {
      // Base chance that a defeated enemy starts item-drop checks.
      chance: {
        base: 0.3,
        // Extra chance added for each enemy rarity step.
        perRarity: 0.15,
        // Maximum chance that any enemy-item roll succeeds after rarity scaling.
        max: 0.9,
        // Multiplier for rarity checks during blood-moon enemy drops.
        bloodMoonMultiplier: 2,
        // Multiplier for rarity checks for dungeon tile enemy drops.
        dungeonMultiplier: 3,
      },
      // Per-kind drop chances checked from minimum to maximum.
      // Each kind is evaluated in this order; a proc adds that drop and the
      // process continues to the next higher chance.
      kindChances: {
        artifact: 0.08,
        armor: 0.16,
        offhand: 0.2,
        weapon: 0.22,
        consumable: 0.34,
      },
      bonuses: {
        // Extra blood-moon minimum-tier bonus calculation for monster loot.
        bloodMoon: {
          // Minimum tier bonus when dropping blood-moon rewards.
          minimumTierBonus: 1,
          // Rarity rank step that grants one extra tier bonus.
          rarityStep: 2,
        },
        // Animal-skinned loot scaling values.
        skinnedAnimal: {
          // Base minimum skinned quantity.
          minimum: 1,
          // Divider used for tier scaling on skinning quantity.
          tierDivisor: 2,
          // Additional skinned quantity added during blood moon.
          bloodMoonBonus: 1,
        },
      },
    },
    gatheringByproduct: {
      // Chance that tree gathering awards a byproduct resource.
      tree: 0.35,
      // Chance that ore gathering awards a byproduct resource.
      ore: 0.3,
    },
    bloodMoonItemKind: {
      // Weight for artifact drops in blood moon bonus item rolls.
      artifact: 0.2,
      // Weight for weapon drops in blood moon bonus item rolls.
      weapon: 0.3,
      // Weight for offhand drops in blood moon bonus item rolls.
      offhand: 0.25,
      // Weight for armor drops in blood moon bonus item rolls.
      armor: 0.25,
    },
  },
  territories: {
    factionRegion: {
      // Chance that an eligible generated region becomes a faction territory.
      spawn: 0.17,
    },
    structures: {
      // Weight for a faction territory to generate a forge.
      forge: 0.1,
      // Weight for a faction territory to generate a workshop.
      workshop: 0.12,
      // Weight for a faction territory to generate a camp.
      camp: 0.12,
      // Weight for a faction territory to generate no extra structure.
      none: 0.66,
    },
  },
} as const);

export default gameConfig;
