packages:
  - 'packages/*'
fund: false
minimumReleaseAge: 0
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
overrides:
  '@xmldom/xmldom': '0.8.13'
  'serialize-javascript@<=7.0.2': '>=7.0.3'
  'serialize-javascript@<7.0.5': '>=7.0.5'
  axios@>=1.0.0 <1.15.1: ^1.15.1
  axios@>=1.0.0 <1.15.2: ^1.15.2
  basic-ftp@<=5.3.0: ^5.3.1
  ip-address@<=10.1.0: ^10.1.1
