import { createSkillRecord } from '../../../../../game/skillRecords';
import type { HeroOverview, HeroWindowProps } from '../../types';

export const heroWindowHero: HeroOverview = {
  hp: 10,
  maxHp: 10,
  mana: 5,
  maxMana: 5,
  xp: 0,
  nextLevelXp: 10,
  rawAttack: 1,
  rawDefense: 1,
  attack: 1,
  defense: 1,
  attackSpeed: 1.25,
  bonusExperience: 143,
  criticalStrikeChance: 15,
  criticalStrikeDamage: 175,
  lifestealChance: 10,
  lifestealAmount: 8,
  dodgeChance: 12,
  blockChance: 18,
  suppressDamageChance: 6,
  suppressDamageReduction: 35,
  suppressDebuffChance: 9,
  bleedChance: 11,
  poisonChance: 13,
  burningChance: 14,
  chillingChance: 7,
  powerBuffChance: 5,
  frenzyBuffChance: 4,
  secondaryStatTotals: {
    attackSpeed: { effective: 1.25, raw: 1.25 },
    bonusExperience: { effective: 143, raw: 143 },
    criticalStrikeChance: { effective: 75, raw: 143 },
    criticalStrikeDamage: { effective: 175, raw: 243 },
    lifestealChance: { effective: 10, raw: 10 },
    lifestealAmount: { effective: 8, raw: 8 },
    dodgeChance: { effective: 12, raw: 12 },
    blockChance: { effective: 18, raw: 18 },
    suppressDamageChance: { effective: 6, raw: 6 },
    suppressDamageReduction: { effective: 35, raw: 35 },
    suppressDebuffChance: { effective: 9, raw: 9 },
    bleedChance: { effective: 11, raw: 11 },
    poisonChance: { effective: 13, raw: 13 },
    burningChance: { effective: 14, raw: 14 },
    chillingChance: { effective: 7, raw: 7 },
    powerBuffChance: { effective: 5, raw: 5 },
    frenzyBuffChance: { effective: 4, raw: 4 },
  },
  statusEffects: [],
  buffs: [],
  debuffs: [],
  abilityIds: [],
  level: 1,
  masteryLevel: 0,
  skills: createSkillRecord(() => ({ level: 1, xp: 0 })),
};

export function buildHeroWindowProps(
  overrides: Partial<HeroWindowProps> = {},
): HeroWindowProps {
  return {
    position: { x: 16, y: 24 },
    onMove: () => undefined,
    visible: true,
    hero: heroWindowHero,
    hunger: 0,
    thirst: 0,
    ...overrides,
  };
}
