import { GAME_TAGS } from './tags';
import { GENERATED_ICON_POOLS } from './generatedIconPools';
import { itemName } from './i18n';
import { EquipmentSlotId } from './ids';
import type { ItemConfig } from './types';

type FamilyKey = keyof typeof GENERATED_ICON_POOLS;

interface GeneratedCraftingFamily {
  familyKey: FamilyKey;
  keyPrefix: string;
  label: string;
  slot: ItemConfig['slot'];
  category: NonNullable<ItemConfig['category']>;
  tier: number;
  rarity: ItemConfig['rarity'];
  power: number;
  defense: number;
  maxHp: number;
  occupiesOffhand?: boolean;
}

const GENERATED_CRAFTING_FAMILIES: GeneratedCraftingFamily[] = [
  {
    familyKey: 'helmet',
    keyPrefix: 'icon-helmet',
    label: 'Helmet',
    slot: EquipmentSlotId.Head,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 2,
    maxHp: 1,
  },
  {
    familyKey: 'shoulders',
    keyPrefix: 'icon-shoulders',
    label: 'Shoulders',
    slot: EquipmentSlotId.Shoulders,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 2,
    maxHp: 1,
  },
  {
    familyKey: 'chest',
    keyPrefix: 'icon-chest',
    label: 'Chest Armor',
    slot: EquipmentSlotId.Chest,
    category: 'armor',
    tier: 3,
    rarity: 'common',
    power: 0,
    defense: 3,
    maxHp: 2,
  },
  {
    familyKey: 'bracers',
    keyPrefix: 'icon-bracers',
    label: 'Bracers',
    slot: EquipmentSlotId.Bracers,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 1,
    maxHp: 1,
  },
  {
    familyKey: 'gloves',
    keyPrefix: 'icon-gloves',
    label: 'Gloves',
    slot: EquipmentSlotId.Hands,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 1,
    maxHp: 1,
  },
  {
    familyKey: 'belt',
    keyPrefix: 'icon-belt',
    label: 'Belt',
    slot: EquipmentSlotId.Belt,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 1,
    maxHp: 1,
  },
  {
    familyKey: 'leggings',
    keyPrefix: 'icon-leggings',
    label: 'Leggings',
    slot: EquipmentSlotId.Legs,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 2,
    maxHp: 1,
  },
  {
    familyKey: 'feet',
    keyPrefix: 'icon-boots',
    label: 'Boots',
    slot: EquipmentSlotId.Feet,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 1,
    maxHp: 1,
  },
  {
    familyKey: 'cloak',
    keyPrefix: 'icon-cloak',
    label: 'Cloak',
    slot: EquipmentSlotId.Cloak,
    category: 'armor',
    tier: 2,
    rarity: 'common',
    power: 0,
    defense: 1,
    maxHp: 2,
  },
  {
    familyKey: 'axe',
    keyPrefix: 'icon-axe',
    label: 'Axe',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 3,
    rarity: 'common',
    power: 5,
    defense: 0,
    maxHp: 0,
  },
  {
    familyKey: 'sword',
    keyPrefix: 'icon-sword',
    label: 'Sword',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 3,
    rarity: 'common',
    power: 5,
    defense: 0,
    maxHp: 0,
  },
  {
    familyKey: 'mace',
    keyPrefix: 'icon-mace',
    label: 'Mace',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 3,
    rarity: 'common',
    power: 5,
    defense: 0,
    maxHp: 1,
  },
  {
    familyKey: 'dagger',
    keyPrefix: 'icon-dagger',
    label: 'Dagger',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 2,
    rarity: 'common',
    power: 4,
    defense: 0,
    maxHp: 0,
  },
  {
    familyKey: 'dagger',
    keyPrefix: 'icon-offhand-dagger',
    label: 'Parrying Dagger',
    slot: EquipmentSlotId.Offhand,
    category: 'weapon',
    tier: 2,
    rarity: 'common',
    power: 3,
    defense: 0,
    maxHp: 0,
  },
  {
    familyKey: 'wand',
    keyPrefix: 'icon-wand',
    label: 'Wand',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 3,
    rarity: 'uncommon',
    power: 6,
    defense: 0,
    maxHp: 0,
  },
  {
    familyKey: 'magicalSphere',
    keyPrefix: 'icon-magical-sphere',
    label: 'Magical Sphere',
    slot: EquipmentSlotId.Offhand,
    category: 'artifact',
    tier: 4,
    rarity: 'uncommon',
    power: 2,
    defense: 0,
    maxHp: 3,
  },
  {
    familyKey: 'shield',
    keyPrefix: 'icon-shield',
    label: 'Shield',
    slot: EquipmentSlotId.Offhand,
    category: 'armor',
    tier: 3,
    rarity: 'common',
    power: 0,
    defense: 4,
    maxHp: 2,
  },
  {
    familyKey: 'twoHandedSword',
    keyPrefix: 'icon-two-handed-sword',
    label: 'Two-Handed Sword',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 4,
    rarity: 'uncommon',
    power: 8,
    defense: 0,
    maxHp: 2,
    occupiesOffhand: true,
  },
  {
    familyKey: 'twoHandedAxe',
    keyPrefix: 'icon-two-handed-axe',
    label: 'Two-Handed Axe',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 4,
    rarity: 'uncommon',
    power: 8,
    defense: 0,
    maxHp: 2,
    occupiesOffhand: true,
  },
  {
    familyKey: 'twoHandedMace',
    keyPrefix: 'icon-two-handed-mace',
    label: 'Two-Handed Mace',
    slot: EquipmentSlotId.Weapon,
    category: 'weapon',
    tier: 4,
    rarity: 'uncommon',
    power: 8,
    defense: 0,
    maxHp: 3,
    occupiesOffhand: true,
  },
  {
    familyKey: 'ring',
    keyPrefix: 'icon-ring',
    label: 'Ring',
    slot: EquipmentSlotId.RingLeft,
    category: 'artifact',
    tier: 3,
    rarity: 'uncommon',
    power: 2,
    defense: 0,
    maxHp: 2,
  },
  {
    familyKey: 'necklace',
    keyPrefix: 'icon-necklace',
    label: 'Necklace',
    slot: EquipmentSlotId.Amulet,
    category: 'artifact',
    tier: 3,
    rarity: 'uncommon',
    power: 1,
    defense: 1,
    maxHp: 3,
  },
];

function padIndex(index: number) {
  return String(index + 1).padStart(2, '0');
}

export const CRAFTABLE_ICON_ITEM_CONFIGS: ItemConfig[] =
  GENERATED_CRAFTING_FAMILIES.flatMap((family) =>
    GENERATED_ICON_POOLS[family.familyKey].map((icon, index) => {
      const ordinal = padIndex(index);
      return {
        key: `${family.keyPrefix}-${ordinal}`,
        name: itemName(`${family.keyPrefix}-${ordinal}`),
        slot: family.slot,
        icon,
        category: family.category,
        tier: family.tier,
        rarity: family.rarity,
        power: family.power,
        defense: family.defense,
        maxHp: family.maxHp,
        healing: 0,
        hunger: 0,
        thirst: 0,
        occupiesOffhand: family.occupiesOffhand,
        tags: [GAME_TAGS.item.crafted],
      } satisfies ItemConfig;
    }),
  );
