export enum GameTag {
  ItemStackable = 'item.stackable',
  ItemConsumable = 'item.consumable',
  ItemResource = 'item.resource',
  ItemEquipment = 'item.equipment',
  ItemWeapon = 'item.weapon',
  ItemArmor = 'item.armor',
  ItemArtifact = 'item.artifact',
  ItemFood = 'item.food',
  ItemDrink = 'item.drink',
  ItemHealing = 'item.healing',
  ItemRecipe = 'item.recipe',
  ItemRecipeBook = 'item.recipeBook',
  ItemCurrency = 'item.currency',
  ItemProspectable = 'item.prospectable',
  ItemCrafted = 'item.crafted',
  ItemGathered = 'item.gathered',
  ItemAnimalProduct = 'item.animalProduct',
  ItemOre = 'item.ore',
  ItemWood = 'item.wood',
  ItemCloth = 'item.cloth',
  ItemAether = 'item.aether',
  ItemHomeward = 'item.homeward',
  ItemTotem = 'item.totem',
  EnemyHostile = 'enemy.hostile',
  EnemyAnimal = 'enemy.animal',
  EnemyBeast = 'enemy.beast',
  EnemyHumanoid = 'enemy.humanoid',
  EnemyAberration = 'enemy.aberration',
  EnemyWorldBoss = 'enemy.worldBoss',
  EnemyElite = 'enemy.elite',
  EnemyDungeon = 'enemy.dungeon',
  StatusBuff = 'status.buff',
  StatusDebuff = 'status.debuff',
  StatusSurvival = 'status.survival',
  StatusRestoration = 'status.restoration',
  StatusDeath = 'status.death',
  StatusHunger = 'status.hunger',
  StatusThirst = 'status.thirst',
}

export const GAME_TAGS = {
  item: {
    stackable: GameTag.ItemStackable,
    consumable: GameTag.ItemConsumable,
    resource: GameTag.ItemResource,
    equipment: GameTag.ItemEquipment,
    weapon: GameTag.ItemWeapon,
    armor: GameTag.ItemArmor,
    artifact: GameTag.ItemArtifact,
    food: GameTag.ItemFood,
    drink: GameTag.ItemDrink,
    healing: GameTag.ItemHealing,
    recipe: GameTag.ItemRecipe,
    recipeBook: GameTag.ItemRecipeBook,
    currency: GameTag.ItemCurrency,
    prospectable: GameTag.ItemProspectable,
    crafted: GameTag.ItemCrafted,
    gathered: GameTag.ItemGathered,
    animalProduct: GameTag.ItemAnimalProduct,
    ore: GameTag.ItemOre,
    wood: GameTag.ItemWood,
    cloth: GameTag.ItemCloth,
    aether: GameTag.ItemAether,
    homeward: GameTag.ItemHomeward,
    totem: GameTag.ItemTotem,
  },
  enemy: {
    hostile: GameTag.EnemyHostile,
    animal: GameTag.EnemyAnimal,
    beast: GameTag.EnemyBeast,
    humanoid: GameTag.EnemyHumanoid,
    aberration: GameTag.EnemyAberration,
    worldBoss: GameTag.EnemyWorldBoss,
    elite: GameTag.EnemyElite,
    dungeon: GameTag.EnemyDungeon,
  },
  status: {
    buff: GameTag.StatusBuff,
    debuff: GameTag.StatusDebuff,
    survival: GameTag.StatusSurvival,
    restoration: GameTag.StatusRestoration,
    death: GameTag.StatusDeath,
    hunger: GameTag.StatusHunger,
    thirst: GameTag.StatusThirst,
  },
} as const;

export const ALL_GAME_TAGS = Object.freeze(
  Object.values(GAME_TAGS).flatMap((group) => Object.values(group)),
);

export function uniqueTags(...tags: Array<GameTag | undefined>) {
  return [...new Set(tags.filter(Boolean))] as GameTag[];
}
