export const CONTENT_ICON_IDS = {
  Player: 'content-icon:player',
  Enemy: 'content-icon:enemy',
  Weapon: 'content-icon:weapon',
  Armor: 'content-icon:armor',
  Artifact: 'content-icon:artifact',
  Consumable: 'content-icon:consumable',
  MagicPotion: 'content-icon:magic-potion',
  Marauder: 'content-icon:marauder',
  Hood: 'content-icon:hood',
  Gauntlet: 'content-icon:gauntlet',
  Boots: 'content-icon:boots',
  Orb: 'content-icon:orb',
  HornedHelm: 'content-icon:horned-helm',
  Chest: 'content-icon:chest',
  Village: 'content-icon:village',
  DungeonGate: 'content-icon:dungeon-gate',
  Anvil: 'content-icon:anvil',
  AnimalHide: 'content-icon:animal-hide',
  Boar: 'content-icon:boar',
  StonePile: 'content-icon:stone-pile',
  AxeInStump: 'content-icon:axe-in-stump',
  Coins: 'content-icon:coins',
  HerbsBundle: 'content-icon:herbs-bundle',
  Beet: 'content-icon:beet',
  BellPepper: 'content-icon:bell-pepper',
  Cabbage: 'content-icon:cabbage',
  Carrot: 'content-icon:carrot',
  Cherry: 'content-icon:cherry',
  Garlic: 'content-icon:garlic',
  Leek: 'content-icon:leek',
  Lemon: 'content-icon:lemon',
  Log: 'content-icon:log',
  Ore: 'content-icon:ore',
  GoldBar: 'content-icon:gold-bar',
  Peas: 'content-icon:peas',
  Salmon: 'content-icon:salmon',
  ShinyApple: 'content-icon:shiny-apple',
  Sparkles: 'content-icon:sparkles',
  Stag: 'content-icon:stag',
  Steak: 'content-icon:steak',
  StoneBlock: 'content-icon:stone-block',
  Spill: 'content-icon:spill',
  SunCloud: 'content-icon:sun-cloud',
  Raining: 'content-icon:raining',
  Snowing: 'content-icon:snowing',
  HighGrass: 'content-icon:high-grass',
  Flax: 'content-icon:flax',
  Tomato: 'content-icon:tomato',
  Totem: 'content-icon:totem',
  WoodStick: 'content-icon:wood-stick',
  BookCover: 'content-icon:book-cover',
  FriedFish: 'content-icon:fried-fish',
  CampCookingPot: 'content-icon:camp-cooking-pot',
  StoneCrafting: 'content-icon:stone-crafting',
  Aubergine: 'content-icon:aubergine',
  Spider: 'content-icon:spider',
  TiedScroll: 'content-icon:tied-scroll',
  RolledCloth: 'content-icon:rolled-cloth',
  Raider: 'content-icon:raider',
  Gluttony: 'content-icon:gluttony',
  Furnace: 'content-icon:furnace',
  SewingString: 'content-icon:sewing-string',
  TreasureGoblin: 'content-icon:treasure-goblin',
  Lockpicks: 'content-icon:lockpicks',
  LockedChest: 'content-icon:locked-chest',
  ChestKey: 'content-icon:chest-key',
  EarthCrack: 'content-icon:earth-crack',
} as const;

export type ContentIconId = (typeof CONTENT_ICON_IDS)[keyof typeof CONTENT_ICON_IDS];

export const ABILITY_ICON_IDS = {
  kick: 'ability-icon:kick',
  slash: 'ability-icon:slash',
  crushingBlow: 'ability-icon:crushing-blow',
  hamstring: 'ability-icon:hamstring',
  whirlwind: 'ability-icon:whirlwind',
  impale: 'ability-icon:impale',
  emberShot: 'ability-icon:ember-shot',
  fireball: 'ability-icon:fireball',
  searingNova: 'ability-icon:searing-nova',
  cinderBurst: 'ability-icon:cinder-burst',
  magmaStrike: 'ability-icon:magma-strike',
  wildfire: 'ability-icon:wildfire',
  sparkJolt: 'ability-icon:spark-jolt',
  arcBolt: 'ability-icon:arc-bolt',
  thunderClap: 'ability-icon:thunder-clap',
  chainLightning: 'ability-icon:chain-lightning',
  stormSurge: 'ability-icon:storm-surge',
  staticField: 'ability-icon:static-field',
  frostShard: 'ability-icon:frost-shard',
  iceLance: 'ability-icon:ice-lance',
  freezingWave: 'ability-icon:freezing-wave',
  coldSnap: 'ability-icon:cold-snap',
  blizzard: 'ability-icon:blizzard',
  brainFreeze: 'ability-icon:brain-freeze',
  mendWounds: 'ability-icon:mend-wounds',
  fieldDressing: 'ability-icon:field-dressing',
  soothingMist: 'ability-icon:soothing-mist',
  rallyingCry: 'ability-icon:rallying-cry',
  battlePrayer: 'ability-icon:battle-prayer',
  warBanner: 'ability-icon:war-banner',
  arcWard: 'ability-icon:arc-ward',
  witheringHex: 'ability-icon:withering-hex',
  sunderArmor: 'ability-icon:sunder-armor',
  enfeeblingPulse: 'ability-icon:enfeebling-pulse',
  ironGuard: 'ability-icon:iron-guard',
} as const;

export type AbilityIconId = (typeof ABILITY_ICON_IDS)[keyof typeof ABILITY_ICON_IDS];

export const STATUS_EFFECT_ICON_IDS = {
  hunger: 'status-effect-icon:hunger',
  thirst: 'status-effect-icon:thirst',
  recentDeath: 'status-effect-icon:recent-death',
  restoration: 'status-effect-icon:restoration',
  bleeding: 'status-effect-icon:bleeding',
  poison: 'status-effect-icon:poison',
  burning: 'status-effect-icon:burning',
  chilling: 'status-effect-icon:chilling',
  power: 'status-effect-icon:power',
  frenzy: 'status-effect-icon:frenzy',
  guard: 'status-effect-icon:guard',
  weakened: 'status-effect-icon:weakened',
  shocked: 'status-effect-icon:shocked',
} as const;

export type StatusEffectIconId =
  (typeof STATUS_EFFECT_ICON_IDS)[keyof typeof STATUS_EFFECT_ICON_IDS];

export type GameplayIconId = ContentIconId | AbilityIconId | StatusEffectIconId;
